In [3]:
import numpy as np

In [4]:
arr = np.random.rand(4)

In [5]:
arr

array([0.32859972, 0.77938773, 0.57742662, 0.3653814 ])

In [6]:
sorted_arr = np.sort(arr)

In [7]:
sorted_arr

array([0.32859972, 0.3653814 , 0.57742662, 0.77938773])

array([0.32859972, 0.77938773, 0.57742662, 0.3653814 ])

In [9]:
arr.sort()

In [10]:
arr

array([0.32859972, 0.3653814 , 0.57742662, 0.77938773])

In [11]:
rev_arr = -np.sort(-arr) #descending arr

In [12]:
rev_arr

array([0.77938773, 0.57742662, 0.3653814 , 0.32859972])

In [13]:
#2d ara
arr2d = np.random.randn(2,4)

In [14]:
arr2d

array([[ 1.28014524,  2.20904011, -0.33580411,  1.13490633],
       [ 0.63378636, -0.78719948, -0.91592499,  0.18367853]])

In [15]:
# axis0 __ row
row_srt = np.sort(arr2d,axis=0)

In [17]:
row_srt

array([[ 0.63378636, -0.78719948, -0.91592499,  0.18367853],
       [ 1.28014524,  2.20904011, -0.33580411,  1.13490633]])

In [18]:
col_srt = np.sort(arr2d,axis =1 )

In [20]:
col_srt # axis =1 

array([[-0.33580411,  1.13490633,  1.28014524,  2.20904011],
       [-0.91592499, -0.78719948,  0.18367853,  0.63378636]])