In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# binary mode
np.save('data',arr)

In [5]:
arr2 = np.load('data.npy')

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = np.arange(20)

In [9]:
np.savez('arrays',a=arr,b=arr2)

In [10]:
arrs = np.load('arrays.npz',)

In [11]:
arrs

In [12]:
arrs['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arrs['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez_compressed('arrar_comp.npz',a=arr,b=arr3)

In [15]:
comp = np.load('arrar_comp.npz')

In [16]:
comp

In [18]:
comp['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])