In [1]:
import numpy as np

In [2]:
dtype

NameError: name 'dtype' is not defined

In [4]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [8]:
arr1

array([1., 2., 3.])

In [10]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [12]:
arr2

array([1, 2, 3])

In [13]:
arr1

array([1., 2., 3.])

In [14]:
arr1.dtype

dtype('float64')

dtype('int32')

dtype('int32')

In [17]:
arr = np.array([1,2,3,4])

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
arr.dtype

dtype('int32')

In [20]:
float_arr = arr.astype(np.float64)

In [21]:
float_arr

array([1., 2., 3., 4.])

In [22]:
arr.dtype

dtype('int32')

In [23]:
float_arr.dtype

dtype('float64')

In [24]:
float_arr

array([1., 2., 3., 4.])

In [25]:
data = np.array([3.4,5.7,1.8,4])

In [26]:
data.dtype

dtype('float64')

In [27]:
data

array([3.4, 5.7, 1.8, 4. ])

In [28]:
intarr=data.astype(np.int64)

In [29]:
intarr

array([3, 5, 1, 4], dtype=int64)