In [1]:
import numpy as np

In [11]:
names = np.array(['Hasan','Hasai','Elyor','Gypsy','Hasan','Aza','Yettei'])

In [8]:
names.size

7

In [4]:
data = np.random.randn(7,4)

In [5]:
data

array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [12]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [18]:
print(names)
data

['Hasan' 'Hasai' 'Elyor' 'Gypsy' 'Hasan' 'Aza' 'Yettei']


array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [14]:
data[names == 'Hasan']

array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713]])

In [16]:
data[names == 'Gypsy']

array([[ 0.62248321, -0.12260303, -0.65606749, -0.36891669]])

In [17]:
data[names == 'Hasan',2:]

array([[-0.09840229,  1.80920116],
       [ 0.30295265, -0.89898713]])

In [19]:
data[names != 'Hasan']

array([[-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [21]:
data[~(names=='Hasan')] # not equal

array([[-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [22]:
print(names)

['Hasan' 'Hasai' 'Elyor' 'Gypsy' 'Hasan' 'Aza' 'Yettei']


In [23]:
data


array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [24]:
mask = (names == 'Hasan') | (names=='Gypsy')

In [25]:
mask

array([ True, False, False,  True,  True, False, False])

In [26]:
data[mask]

array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713]])

In [27]:
data

array([[-0.41933347,  0.24905745, -0.09840229,  1.80920116],
       [-0.27556409,  0.10508247, -0.29613379, -0.78703773],
       [-0.5485216 , -1.07902778,  0.83220462,  0.44554589],
       [ 0.62248321, -0.12260303, -0.65606749, -0.36891669],
       [-0.42117614,  0.8783545 ,  0.30295265, -0.89898713],
       [-0.01490577,  0.49678404,  1.4068701 , -2.13626432],
       [ 0.3952459 ,  0.31519102,  1.27641995,  1.76370821]])

In [29]:
data[data<0
    ]=0

In [30]:
data

array([[0.        , 0.24905745, 0.        , 1.80920116],
       [0.        , 0.10508247, 0.        , 0.        ],
       [0.        , 0.        , 0.83220462, 0.44554589],
       [0.62248321, 0.        , 0.        , 0.        ],
       [0.        , 0.8783545 , 0.30295265, 0.        ],
       [0.        , 0.49678404, 1.4068701 , 0.        ],
       [0.3952459 , 0.31519102, 1.27641995, 1.76370821]])