In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [12]:
np.log(arr)

<ipython-input-12-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
arr1 = np.random.randn(6)

In [17]:
arr1

array([-0.4339799 , -1.31603387,  1.40535004, -1.87488465, -0.86488823,
        0.69415696])

In [20]:
kaldik,butun = np.modf(arr1)

In [21]:
kaldik

array([-0.4339799 , -0.31603387,  0.40535004, -0.87488465, -0.86488823,
        0.69415696])

In [24]:
arr1


array([-0.4339799 , -1.31603387,  1.40535004, -1.87488465, -0.86488823,
        0.69415696])

In [23]:
np.sign(arr1)

array([-1., -1.,  1., -1., -1.,  1.])

In [27]:
np.isnan(arr1) # return if there is no non value

array([False, False, False, False, False, False])

In [28]:
arr1[0]=np.NaN

In [29]:
arr1

array([        nan, -1.31603387,  1.40535004, -1.87488465, -0.86488823,
        0.69415696])

In [30]:
np.isnan(arr1
        )

array([ True, False, False, False, False, False])

# binaryfunction

In [32]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [33]:
arr2

array([-1.99619786,  0.61409469,  1.6821968 , -0.07533165,  0.72296272,
        1.51300003])

In [34]:
arr3

array([ 0.65025566,  0.75018964,  2.26518378, -0.22241773,  0.5081031 ,
       -1.45351003])

In [35]:
np.add(arr2,arr3)

array([-1.3459422 ,  1.36428433,  3.94738058, -0.29774938,  1.23106582,
        0.05949   ])

In [36]:
arr2+arr3

array([-1.3459422 ,  1.36428433,  3.94738058, -0.29774938,  1.23106582,
        0.05949   ])

In [37]:
np.multiply(arr2,arr3)

array([-1.29803896,  0.46068747,  3.8104849 ,  0.01675509,  0.3673396 ,
       -2.19916073])

In [38]:
arr2*arr3

array([-1.29803896,  0.46068747,  3.8104849 ,  0.01675509,  0.3673396 ,
       -2.19916073])

In [39]:
np.multiply(arr2,arr3)

array([-1.29803896,  0.46068747,  3.8104849 ,  0.01675509,  0.3673396 ,
       -2.19916073])

In [40]:
np.maximum(arr2,arr3)

array([ 0.65025566,  0.75018964,  2.26518378, -0.07533165,  0.72296272,
        1.51300003])