In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)

In [4]:
arr

array([[ 0.26821466, -0.5820023 , -0.03792773, -0.01230411],
       [-0.07612742, -0.25433216, -0.72698402,  0.50988091],
       [-1.41008945,  0.89150696, -1.06512516,  1.84118924],
       [ 0.90988542, -2.33656418,  0.72042541,  1.35957098],
       [-0.13556719,  0.77849051, -0.29368655, -0.14931018]])

In [6]:
arr.sum()

0.19914363320104136

In [7]:
np.sum(arr)

0.19914363320104136

In [9]:
arr.sum(axis=0) # column sum

array([-0.44368398, -1.50290117, -1.40329806,  3.54902685])

In [10]:
arr.sum(axis=1) # row sum

array([-0.36401947, -0.54756269,  0.25748159,  0.65331762,  0.19992658])

In [11]:
data =  np.arange(5)

In [12]:
data

array([0, 1, 2, 3, 4])

In [13]:
mean = np.sum(data)/len(data)

In [14]:
mean

2.0

In [15]:
np.mean(arr)

0.009957181660052068

In [16]:
np.mean(data)

2.0

In [17]:
data.mean()

2.0

In [18]:
arr.mean()

0.009957181660052068

In [19]:
np.mean(arr)

0.009957181660052068

In [21]:
np.mean(arr,axis=1)

array([-0.09100487, -0.13689067,  0.0643704 ,  0.1633294 ,  0.04998165])

In [22]:
arr.mean(axis=0)

array([-0.0887368 , -0.30058023, -0.28065961,  0.70980537])

In [23]:
data

array([0, 1, 2, 3, 4])

In [24]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10], dtype=int32)