In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y = np.array([[6,23],[-1,7],[8,9]])

In [5]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [6]:
#dot
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [7]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [8]:
np.dot(y,x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [11]:
from numpy.linalg import inv as i

NameError: name 'i' is not defined